language: python
sudo: false

git:
  submodules: false


matrix:
  include:
    - os: linux
      python: 3

install:
  - pip$PYTHON_VERSION install --upgrade setuptools
  - pip$PYTHON_VERSION install --upgrade -e.[test]

script:
  - python$PYTHON_VERSION setup.py test